# Generated by Django 5.0 on 2024-03-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
