# Generated by Django 4.2.5 on 2024-02-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('short_description', models.CharField(max_length=260)),
                ('description', models.TextField(help_text='describe the product here')),
                ('slug', models.SlugField()),
                ('is_active', models.BooleanField()),
                ('is_delete', models.BooleanField(default=False)),
                ('picture', models.ImageField(upload_to='product')),
                ('category', models.ManyToManyField(to='product.productcategory')),
            ],
        ),
    ]
