# Generated by Django 5.0.1 on 2024-01-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(null=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
