# Generated by Django 5.0.1 on 2024-01-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productcategory'),
        ('product', '0003_alter_product_description_and_more'),
    ]

    operations = [
    ]
