# Generated by Django 5.0.1 on 2024-01-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_merge_20240130_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='is_delete',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
