# Generated by Django 5.0.3 on 2024-04-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pesronal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phone', models.IntegerField(max_length=12)),
                ('id_number', models.IntegerField(max_length=10, unique=True)),
                ('cart_number', models.IntegerField(max_length=16)),
            ],
        ),
    ]
