# Generated by Django 5.0.3 on 2024-04-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0002_alter_pesronal_info_cart_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesronal_info',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
