# Generated by Django 5.0.3 on 2024-04-24 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0003_pesronal_info_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pesronal_info',
        ),
    ]
